# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config.nixos.laptop =
    {
      config,
      lib,
      pkgs,
      modulesPath,
      ...
    }:
    {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "thunderbolt"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/luks-95ed6ab1-b26b-4181-aaf0-77a58e44c0c9";
    fsType = "btrfs";
  };

  boot.initrd.luks.devices."luks-95ed6ab1-b26b-4181-aaf0-77a58e44c0c9".device =
    "/dev/disk/by-uuid/95ed6ab1-b26b-4181-aaf0-77a58e44c0c9";

  fileSystems."/home" = {
    device = "/dev/mapper/luks-95ed6ab1-b26b-4181-aaf0-77a58e44c0c9";
    fsType = "btrfs";
    options = [ "subvol=home" ];
  };

  fileSystems."/nix" = {
    device = "/dev/mapper/luks-95ed6ab1-b26b-4181-aaf0-77a58e44c0c9";
    fsType = "btrfs";
    options = [ "subvol=nix" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/CB58-F16C";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
    };
}
