# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config.nixos.desktop =
    {
      config,
      lib,
      pkgs,
      modulesPath,
      ...
    }:
    {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "usb_storage"
    "usbhid"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/luks-39a89e32-c890-4ff9-842e-34c16a497231";
    fsType = "btrfs";
  };

  boot.initrd.luks.devices = {
    "luks-39a89e32-c890-4ff9-842e-34c16a497231".device =
      "/dev/disk/by-uuid/39a89e32-c890-4ff9-842e-34c16a497231";
    "luks-d57a23be-cf31-405e-ac09-9cb06e6331c1".device =
      "/dev/disk/by-uuid/d57a23be-cf31-405e-ac09-9cb06e6331c1";
    "luks-5a37508d-66a3-40ba-a228-cdeb5606e521".device =
      "/dev/disk/by-uuid/5a37508d-66a3-40ba-a228-cdeb5606e521";
  };

  fileSystems."/home" = {
    device = "/dev/mapper/luks-39a89e32-c890-4ff9-842e-34c16a497231";
    fsType = "btrfs";
    options = [ "subvol=home" ];
  };

  fileSystems."/nix" = {
    device = "/dev/mapper/luks-39a89e32-c890-4ff9-842e-34c16a497231";
    fsType = "btrfs";
    options = [ "subvol=nix" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/F9A5-37B4";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
    };
}
